<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Service;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ServiceSeeder extends Seeder
{
    public function run(): void
    {
        $barbershops = Category::where('slug', 'barbershops')->first();
        $nailSalons = Category::where('slug', 'nail-salons')->first();
        $restaurants = Category::where('slug', 'restaurants')->first();
        $coffeeShops = Category::where('slug', 'coffee-shops')->first();
        $petGrooming = Category::where('slug', 'pet-grooming')->first();
        $fitness = Category::where('slug', 'fitness-gyms')->first();
        $spa = Category::where('slug', 'spa-massage')->first();
        $beautySalons = Category::where('slug', 'beauty-salons')->first();

        // Get service provider users to assign as owners
        $serviceProviders = User::where('is_service_provider', true)->get();
        $providerIndex = 0;

        $services = [
            // ── Barbershops ─────────────────────────────────────────────────────
            [
                'category_id' => $barbershops->id,
                'name' => 'Classic Cuts Barbershop',
                'description' => 'Traditional barbershop offering classic haircuts, beard trims, and hot towel shaves. Our experienced barbers bring old-school craftsmanship to modern styling.',
                'price_range' => 2,
                'badge' => 'BEST VALUE',
                'badge_color' => 'green',
                'is_available' => true,
                'available_at' => 'Available today at 10:00 AM',
                'rating' => 4.8,
                'reviews_count' => 342,
                'city' => 'New York',
                'state' => 'NY',
                'address' => '123 Main St, New York, NY 10001',
                'opening_hours' => 'Mon - Fri: 9:00 AM - 7:00 PM | Sat: 9:00 AM - 5:00 PM',
                'latitude' => 40.7484,
                'longitude' => -73.9857,
            ],
            [
                'category_id' => $barbershops->id,
                'name' => 'Urban Fade Studio',
                'description' => 'Modern barbershop specializing in fades, designs, and creative hairstyles. Walk-ins welcome or book your appointment online.',
                'price_range' => 3,
                'badge' => 'POPULAR',
                'badge_color' => 'blue',
                'is_available' => true,
                'available_at' => 'Available today at 11:30 AM',
                'rating' => 4.9,
                'reviews_count' => 567,
                'city' => 'New York',
                'state' => 'NY',
                'address' => '456 Broadway, New York, NY 10013',
                'opening_hours' => 'Mon - Sat: 10:00 AM - 8:00 PM | Sun: 11:00 AM - 5:00 PM',
                'latitude' => 40.7205,
                'longitude' => -74.0050,
            ],
            [
                'category_id' => $barbershops->id,
                'name' => 'Gentleman\'s Groom Lounge',
                'description' => 'Premium barbershop experience with complimentary beverages, leather chairs, and relaxation amenities. Full grooming services for the modern gentleman.',
                'price_range' => 4,
                'badge' => 'PREMIUM',
                'badge_color' => 'gray',
                'is_available' => true,
                'available_at' => 'Available tomorrow, 9:00 AM',
                'rating' => 4.7,
                'reviews_count' => 189,
                'city' => 'New York',
                'state' => 'NY',
                'address' => '789 5th Ave, New York, NY 10022',
                'opening_hours' => 'Tue - Sat: 9:00 AM - 7:00 PM | Sun: 10:00 AM - 4:00 PM',
                'latitude' => 40.7644,
                'longitude' => -73.9745,
            ],

            // ── Nail Salons ─────────────────────────────────────────────────────
            [
                'category_id' => $nailSalons->id,
                'name' => 'Polished Perfection',
                'description' => 'Full-service nail salon offering manicures, pedicures, nail art, and acrylic extensions. Relax in our spa-like atmosphere.',
                'price_range' => 2,
                'badge' => 'TOP RATED',
                'badge_color' => 'blue',
                'is_available' => true,
                'available_at' => 'Available today at 12:00 PM',
                'rating' => 4.9,
                'reviews_count' => 823,
                'city' => 'New York',
                'state' => 'NY',
                'address' => '321 Lexington Ave, New York, NY 10016',
                'opening_hours' => 'Mon - Sat: 9:00 AM - 8:00 PM | Sun: 10:00 AM - 6:00 PM',
                'latitude' => 40.7527,
                'longitude' => -73.9772,
            ],
            [
                'category_id' => $nailSalons->id,
                'name' => 'Luxe Nail Bar',
                'description' => 'Boutique nail salon with organic nail products and luxury treatments. Specializing in gel manicures and spa pedicures.',
                'price_range' => 3,
                'badge' => 'ECO-FRIENDLY',
                'badge_color' => 'green',
                'is_available' => true,
                'available_at' => 'Available today at 2:00 PM',
                'rating' => 4.8,
                'reviews_count' => 456,
                'city' => 'New York',
                'state' => 'NY',
                'address' => '555 Madison Ave, New York, NY 10022',
                'opening_hours' => 'Mon - Fri: 10:00 AM - 8:00 PM | Sat: 9:00 AM - 7:00 PM',
                'latitude' => 40.7614,
                'longitude' => -73.9712,
            ],
            [
                'category_id' => $nailSalons->id,
                'name' => 'Quick Tips Nail Salon',
                'description' => 'Affordable nail services without compromising quality. Quick manicures and pedicures perfect for busy schedules.',
                'price_range' => 1,
                'badge' => 'FAST SERVICE',
                'badge_color' => 'blue',
                'is_available' => true,
                'available_at' => 'Available today at 1:00 PM',
                'rating' => 4.5,
                'reviews_count' => 298,
                'city' => 'New York',
                'state' => 'NY',
                'address' => '222 W 23rd St, New York, NY 10011',
                'opening_hours' => 'Mon - Sun: 8:00 AM - 9:00 PM',
                'latitude' => 40.7448,
                'longitude' => -73.9973,
            ],

            // ── Restaurants ─────────────────────────────────────────────────────
            [
                'category_id' => $restaurants->id,
                'name' => 'Bella Italia',
                'description' => 'Authentic Italian restaurant serving homemade pasta, wood-fired pizzas, and traditional dishes. Romantic ambiance perfect for date nights.',
                'price_range' => 3,
                'badge' => 'ROMANTIC',
                'badge_color' => 'gray',
                'is_available' => true,
                'available_at' => 'Open now',
                'rating' => 4.7,
                'reviews_count' => 1245,
                'city' => 'New York',
                'state' => 'NY',
                'address' => '100 Spring St, New York, NY 10012',
                'opening_hours' => 'Tue - Thu: 5:00 PM - 10:00 PM | Fri - Sat: 5:00 PM - 11:00 PM | Sun: 12:00 PM - 9:00 PM',
                'latitude' => 40.7225,
                'longitude' => -73.9981,
            ],
            [
                'category_id' => $restaurants->id,
                'name' => 'Dragon Palace',
                'description' => 'Premium Chinese cuisine featuring dim sum, Peking duck, and Szechuan specialties. Family-friendly atmosphere with private dining rooms available.',
                'price_range' => 2,
                'badge' => 'FAMILY FRIENDLY',
                'badge_color' => 'green',
                'is_available' => true,
                'available_at' => 'Open now',
                'rating' => 4.6,
                'reviews_count' => 892,
                'city' => 'New York',
                'state' => 'NY',
                'address' => '88 Canal St, New York, NY 10002',
                'opening_hours' => 'Mon - Sun: 11:00 AM - 10:00 PM',
                'latitude' => 40.7163,
                'longitude' => -73.9982,
            ],
            [
                'category_id' => $restaurants->id,
                'name' => 'The Burger Joint',
                'description' => 'Gourmet burger restaurant with handcrafted patties, creative toppings, and loaded fries. Craft beers and milkshakes available.',
                'price_range' => 2,
                'badge' => 'BEST BURGERS',
                'badge_color' => 'blue',
                'is_available' => true,
                'available_at' => 'Open now',
                'rating' => 4.8,
                'reviews_count' => 1567,
                'city' => 'New York',
                'state' => 'NY',
                'address' => '350 5th Ave, New York, NY 10118',
                'opening_hours' => 'Mon - Sun: 11:00 AM - 10:00 PM',
                'latitude' => 40.7484,
                'longitude' => -73.9857,
            ],

            // ── Coffee Shops ─────────────────────────────────────────────────────
            [
                'category_id' => $coffeeShops->id,
                'name' => 'Morning Brew Café',
                'description' => 'Cozy neighborhood coffee shop serving specialty roasts, fresh pastries, and light breakfast items. Free WiFi and comfortable seating.',
                'price_range' => 1,
                'badge' => 'LOCAL FAVORITE',
                'badge_color' => 'green',
                'is_available' => true,
                'available_at' => 'Open now',
                'rating' => 4.9,
                'reviews_count' => 678,
                'city' => 'New York',
                'state' => 'NY',
                'address' => '175 Orchard St, New York, NY 10002',
                'opening_hours' => 'Mon - Fri: 6:00 AM - 8:00 PM | Sat - Sun: 7:00 AM - 7:00 PM',
                'latitude' => 40.7195,
                'longitude' => -73.9882,
            ],
            [
                'category_id' => $coffeeShops->id,
                'name' => 'Espresso Lab',
                'description' => 'Artisanal coffee shop with single-origin beans, pour-over brewing, and latte art. Perfect for coffee connoisseurs.',
                'price_range' => 2,
                'badge' => 'ARTISANAL',
                'badge_color' => 'blue',
                'is_available' => true,
                'available_at' => 'Open now',
                'rating' => 4.7,
                'reviews_count' => 423,
                'city' => 'New York',
                'state' => 'NY',
                'address' => '200 Church St, New York, NY 10013',
                'opening_hours' => 'Mon - Fri: 7:00 AM - 6:00 PM | Sat - Sun: 8:00 AM - 5:00 PM',
                'latitude' => 40.7168,
                'longitude' => -74.0063,
            ],

            // ── Pet Grooming ─────────────────────────────────────────────────────
            [
                'category_id' => $petGrooming->id,
                'name' => 'Paws & Claws Grooming',
                'description' => 'Full-service pet grooming for dogs and cats. Bathing, haircuts, nail trimming, and ear cleaning. Gentle handling for anxious pets.',
                'price_range' => 2,
                'badge' => 'EXPERIENCED',
                'badge_color' => 'blue',
                'is_available' => true,
                'available_at' => 'Available today at 9:00 AM',
                'rating' => 4.9,
                'reviews_count' => 534,
                'city' => 'New York',
                'state' => 'NY',
                'address' => '45 E 7th St, New York, NY 10003',
                'opening_hours' => 'Mon - Sat: 9:00 AM - 6:00 PM',
                'latitude' => 40.7264,
                'longitude' => -73.9913,
            ],
            [
                'category_id' => $petGrooming->id,
                'name' => 'Happy Tails Spa',
                'description' => 'Luxury pet spa offering grooming, spa treatments, and pampering packages. Organic shampoos and conditioners used.',
                'price_range' => 3,
                'badge' => 'LUXURY',
                'badge_color' => 'gray',
                'is_available' => true,
                'available_at' => 'Available tomorrow, 10:00 AM',
                'rating' => 4.8,
                'reviews_count' => 287,
                'city' => 'New York',
                'state' => 'NY',
                'address' => '120 W 72nd St, New York, NY 10023',
                'opening_hours' => 'Tue - Sat: 9:00 AM - 7:00 PM | Sun: 10:00 AM - 4:00 PM',
                'latitude' => 40.7752,
                'longitude' => -73.9820,
            ],
            [
                'category_id' => $petGrooming->id,
                'name' => 'Mobile Grooming Van',
                'description' => 'Convenient mobile grooming service that comes to your door. Full grooming services in our fully-equipped van.',
                'price_range' => 2,
                'badge' => 'MOBILE',
                'badge_color' => 'green',
                'is_available' => true,
                'available_at' => 'Available today at 11:00 AM',
                'rating' => 4.6,
                'reviews_count' => 198,
                'city' => 'New York',
                'state' => 'NY',
                'address' => 'Serving all NYC boroughs',
                'opening_hours' => 'Mon - Sat: 8:00 AM - 5:00 PM',
                'latitude' => 40.7484,
                'longitude' => -73.9857,
            ],

            // ── Fitness & Gyms ───────────────────────────────────────────────────
            [
                'category_id' => $fitness->id,
                'name' => 'Iron Temple Fitness',
                'description' => 'Traditional gym with free weights, machines, and cardio equipment. Personal training available. 24/7 access for members.',
                'price_range' => 2,
                'badge' => '24/7 ACCESS',
                'badge_color' => 'blue',
                'is_available' => true,
                'available_at' => 'Open now',
                'rating' => 4.5,
                'reviews_count' => 892,
                'city' => 'New York',
                'state' => 'NY',
                'address' => '500 8th Ave, New York, NY 10018',
                'opening_hours' => 'Open 24 Hours',
                'latitude' => 40.7557,
                'longitude' => -73.9903,
            ],
            [
                'category_id' => $fitness->id,
                'name' => 'Zen Yoga Studio',
                'description' => 'Boutique yoga studio offering Vinyasa, Hatha, and Yin yoga classes. Hot yoga and meditation sessions available.',
                'price_range' => 2,
                'badge' => 'TRANQUIL',
                'badge_color' => 'green',
                'is_available' => true,
                'available_at' => 'Open now',
                'rating' => 4.9,
                'reviews_count' => 445,
                'city' => 'New York',
                'state' => 'NY',
                'address' => '25 W 26th St, New York, NY 10010',
                'opening_hours' => 'Mon - Sun: 6:00 AM - 9:00 PM',
                'latitude' => 40.7441,
                'longitude' => -73.9884,
            ],
            [
                'category_id' => $fitness->id,
                'name' => 'CrossFit Manhattan',
                'description' => 'High-intensity functional fitness with group classes and personal training. Open gym hours available for members.',
                'price_range' => 3,
                'badge' => 'HIGH INTENSITY',
                'badge_color' => 'blue',
                'is_available' => true,
                'available_at' => 'Open now',
                'rating' => 4.7,
                'reviews_count' => 312,
                'city' => 'New York',
                'state' => 'NY',
                'address' => '80 White St, New York, NY 10013',
                'opening_hours' => 'Mon - Sat: 5:00 AM - 9:00 PM | Sun: 7:00 AM - 2:00 PM',
                'latitude' => 40.7176,
                'longitude' => -74.0059,
            ],

            // ── Spa & Massage ─────────────────────────────────────────────────────
            [
                'category_id' => $spa->id,
                'name' => 'Serenity Spa & Wellness',
                'description' => 'Full-service day spa offering massages, facials, body treatments, and relaxation therapies. Couples suites available.',
                'price_range' => 4,
                'badge' => 'RELAXATION',
                'badge_color' => 'gray',
                'is_available' => true,
                'available_at' => 'Available today at 2:00 PM',
                'rating' => 4.9,
                'reviews_count' => 678,
                'city' => 'New York',
                'state' => 'NY',
                'address' => '60 Central Park West, New York, NY 10023',
                'opening_hours' => 'Mon - Sat: 9:00 AM - 8:00 PM | Sun: 10:00 AM - 6:00 PM',
                'latitude' => 40.7714,
                'longitude' => -73.9766,
            ],
            [
                'category_id' => $spa->id,
                'name' => 'Healing Hands Massage',
                'description' => 'Therapeutic massage studio specializing in deep tissue, sports massage, and Thai massage. Licensed therapists.',
                'price_range' => 2,
                'badge' => 'THERAPEUTIC',
                'badge_color' => 'blue',
                'is_available' => true,
                'available_at' => 'Available today at 3:00 PM',
                'rating' => 4.8,
                'reviews_count' => 534,
                'city' => 'New York',
                'state' => 'NY',
                'address' => '33 Greenwich Ave, New York, NY 10014',
                'opening_hours' => 'Mon - Fri: 10:00 AM - 9:00 PM | Sat - Sun: 10:00 AM - 6:00 PM',
                'latitude' => 40.7354,
                'longitude' => -74.0022,
            ],
            [
                'category_id' => $spa->id,
                'name' => 'Korean Spa Journey',
                'description' => 'Traditional Korean spa with heat rooms, jacuzzi, and full body scrub treatments. Sauna and relaxation lounge included.',
                'price_range' => 3,
                'badge' => 'TRADITIONAL',
                'badge_color' => 'green',
                'is_available' => true,
                'available_at' => 'Open now',
                'rating' => 4.7,
                'reviews_count' => 892,
                'city' => 'New York',
                'state' => 'NY',
                'address' => '149 W 51st St, New York, NY 10019',
                'opening_hours' => 'Mon - Sun: 6:00 AM - 11:00 PM',
                'latitude' => 40.7614,
                'longitude' => -73.9840,
            ],

            // ── Beauty Salons ─────────────────────────────────────────────────────
            [
                'category_id' => $beautySalons->id,
                'name' => 'Glamour Hair Studio',
                'description' => 'Full-service hair salon offering cuts, coloring, styling, and treatments. Specializing in balayage, highlights, and keratin treatments.',
                'price_range' => 3,
                'badge' => 'EXPERT STYLISTS',
                'badge_color' => 'blue',
                'is_available' => true,
                'available_at' => 'Available today at 11:00 AM',
                'rating' => 4.8,
                'reviews_count' => 756,
                'city' => 'New York',
                'state' => 'NY',
                'address' => '75 5th Ave, New York, NY 10011',
                'opening_hours' => 'Mon - Sat: 9:00 AM - 8:00 PM | Sun: 10:00 AM - 5:00 PM',
                'latitude' => 40.7370,
                'longitude' => -73.9958,
            ],
            [
                'category_id' => $beautySalons->id,
                'name' => 'Blush Beauty Bar',
                'description' => 'Boutique beauty salon offering makeup application, brow shaping, and lash services. Perfect for events and special occasions.',
                'price_range' => 2,
                'badge' => 'EVENT SPECIALISTS',
                'badge_color' => 'gray',
                'is_available' => true,
                'available_at' => 'Available tomorrow, 10:00 AM',
                'rating' => 4.9,
                'reviews_count' => 423,
                'city' => 'New York',
                'state' => 'NY',
                'address' => '155 W 29th St, New York, NY 10001',
                'opening_hours' => 'Tue - Sat: 10:00 AM - 7:00 PM | Sun: 11:00 AM - 4:00 PM',
                'latitude' => 40.7481,
                'longitude' => -73.9924,
            ],
            [
                'category_id' => $beautySalons->id,
                'name' => 'Affordable Cuts & Color',
                'description' => 'Budget-friendly salon offering quality haircuts, coloring, and styling. Walk-ins always welcome.',
                'price_range' => 1,
                'badge' => 'WALK-INS WELCOME',
                'badge_color' => 'green',
                'is_available' => true,
                'available_at' => 'Available today at 12:00 PM',
                'rating' => 4.4,
                'reviews_count' => 567,
                'city' => 'New York',
                'state' => 'NY',
                'address' => '289 Bleecker St, New York, NY 10014',
                'opening_hours' => 'Mon - Sun: 9:00 AM - 8:00 PM',
                'latitude' => 40.7319,
                'longitude' => -74.0027,
            ],
        ];

        foreach ($services as $data) {
            $slug = Str::slug($data['name']);
            $counter = 1;
            $originalSlug = $slug;
            while (Service::where('slug', $slug)->exists()) {
                $slug = $originalSlug.'-'.$counter++;
            }
            
            // Assign a service provider as owner (cycle through available providers)
            $userId = $serviceProviders->isNotEmpty() 
                ? $serviceProviders[$providerIndex % $serviceProviders->count()]->id 
                : null;
            $providerIndex++;
            
            Service::create(array_merge($data, [
                'slug' => $slug,
                'user_id' => $userId,
            ]));
        }
    }
}

